### ISSUE TITLE
wawtuh

### ISSUE THREAD

**Issue by MirkusX** [ThomasR1997/movie-watchlist#1]
![bilde](https://user-images.githubusercontent.com/104134633/227187086-35c73514-b3e4-4014-9fbc-b2481e2308ea.png)

**Comment by ThomasR1997** [comment]
huh? I don't see the issue here
![huh](https://user-images.githubusercontent.com/110661162/227188327-2ea57764-87d5-409b-9f19-2e89856a7ffa.png)

**Comment by MirkusX** [comment]
![waltah](https://user-images.githubusercontent.com/104134633/227189541-43921b55-e74c-43b4-9055-fcd606062845.png)
look closer

**Comment by ThomasR1997** [comment]
Waltuh is that you?
![Skjermbilde 2023-03-23 122741](https://user-images.githubusercontent.com/110661162/227190164-9510c0b7-68af-4ffb-bbae-1337654ad7eb.png)
![Skjermbilde 2023-03-23 122842](https://user-images.githubusercontent.com/110661162/227190332-0a3c915c-c45c-4823-baf2-5db0abc8b86d.png)

**Comment by MirkusX** [comment]
![waltah](https://user-images.githubusercontent.com/104134633/227192869-796a14de-2fcf-4872-880c-426035633d6b.png)
no........its deez

**Comment by ThomasR1997** [comment]
I saw the issue and fixed it. Thank you deez!
![Skjermbilde 2023-03-23 125446](https://user-images.githubusercontent.com/110661162/227196144-77762c9a-a068-494c-a2d4-1bf7622fd234.png)
